# getip package

name: get-ip
parent: default

matches:  
  - trigger: ":getip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.me"

  - trigger: ":winip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.me"
          shell: cmd
